### PR TITLE
Move cc_superset under databend_sqlalchemy

### PR DESCRIPTION
**Pull request by rad-pat**
Superset is looking for `cc_superset` at `databend_sqlalchemy.cc_superset` For issue #29 

@hantmac, does `secure` query param still apply or should it be switched to use `sslmode` now?

### CODE REVIEW

**Comment by rad-pat** [comment]
@hantmac I'm a little confused. The cc_superset.engine code looks older than the version in superset repo. Is the superset repo the correct place to amend this now? If so, why does it still try to load engine spec from dialect?

**Comment by rad-pat** [comment]
Aha, I think I understand. The failure to load the engine spec is ok because in latest superset it already had the spec.  If the superset version is the more recent engine spec then this version should be updated to be the same for people using older version of superset where the engine spec is not defined? Or, the `superset.db_engine_specs` entrypoint and this code needs removing from the dialect.   I think possible the sslmode param needs to be handled in engine spec anyway. Please advise.

**Comment by hantmac** [comment]
> Aha, I think I understand. The failure to load the engine spec is ok because in latest superset it already had the spec. If the superset version is the more recent engine spec then this version should be updated to be the same for people using older version of superset where the engine spec is not defined? Or, the `superset.db_engine_specs` entrypoint and this code needs removing from the dialect. I think possible the sslmode param needs to be handled in engine spec anyway. Please advise.

The `cc_superset` no need to move to `databend_sqlalchemy`, the params were handled in superset code.

**Comment by rad-pat** [comment]
> > Aha, I think I understand. The failure to load the engine spec is ok because in latest superset it already had the spec. If the superset version is the more recent engine spec then this version should be updated to be the same for people using older version of superset where the engine spec is not defined? Or, the `superset.db_engine_specs` entrypoint and this code needs removing from the dialect. I think possible the sslmode param needs to be handled in engine spec anyway. Please advise.
> 
> The `cc_superset` no need to move to `databend_sqlalchemy`, the params were handled in superset code.

Yes, I now think the cc_superset should be removed from this library along with the entrypoint as the code in superset is newer, superset still tries to load (but fails) from package `databend_sqlalchemy.cc_superset.engine.DatabendEngineSpec` because an entrypoint exists in setup.cfg, but package actually exists at `cc_superset.engine.DatabendEngineSpec`. This change happened in commit https://github.com/datafuselabs/databend-sqlalchemy/commit/a31337e60076a097c04a91661f75fb7b03f6d602.  If the code did load successfully from this library, it would override the version in the superset repo. See what you think, I will close this.

**Pull request closed without merging**
