### PR TITLE
Implement TIME type, stored to Databend DateTime type

### PR DESCRIPTION
**Pull request by rad-pat**

### CODE REVIEW

**Comment by rad-pat** [comment]
Huh, tests are failing, but worked ok for me. I guess I'm a good few versions behind on Databend and maybe SQLAlchemy now. I'll update and retry.

**Comment by rad-pat** [comment]
Hi @hantmac . I've been away on vacation 🌞🌴 
This is ready for review, we've been using for a few weeks now. Hopefully you're happy with it and can make a version release please.

**Comment by hantmac** [comment]
> Hi @hantmac . I've been away on vacation 🌞🌴 This is ready for review, we've been using for a few weeks now. Hopefully you're happy with it and can make a version release please.

Thanks ! @rad-pat , hope you have a nice vacation! I will review it as soon as possible.

**Review by hantmac — APPROVED** [review]
LGTM

**Comment by hantmac** [comment]
> Excellent thanks. Are you able to merge and release please?

Of course!

**Comment by hantmac** [comment]
@rad-pat Hi would you like to see this failed test case? https://github.com/datafuselabs/databend-sqlalchemy/actions/runs/10553105522/job/29232947376#step:7:5709

**Pull request merged**
