### PR TITLE
Another fix for views back in system.tables

### PR DESCRIPTION
**Pull request by rad-pat**
Otherwise get duplicate rows - just experienced 🤦

### CODE REVIEW

**Comment by rad-pat** [comment]
Hmmm, I get no test errors running against Databend 1.2.635

**Comment by rad-pat** [comment]
Looks like setting `format_null_as_str` in database, default is 1, turned on. Not sure why you'd want to bring nulls back as a string `NULL` by default.

**Review by TCeason — APPROVED** [review]

**Comment by hantmac** [comment]
@rad-pat HI, the CI TEST failed, plz check it.

**Comment by rad-pat** [comment]
@hantmac I'm pretty sure it's the `format_null_as_str` setting. Is there any way this can be set to `0` on the test Databend instance provisioned for these CI tests? I can try to figure out how to do this from the pytest side before any tests run if required. Or, possibly a param on the connection string?

**Comment by rad-pat** [comment]
@hantmac @TCeason  I've fixed the tests by forcing the `format_null_as_str` option on every connection. This doesn't seem like a good approach going forward. Ideally would like to pass the param on the connection string to the bendsql driver.

**Review by TCeason — APPROVED** [review]

**Review by hantmac — APPROVED** [review]
LGTM

**Comment by hantmac** [comment]
> @hantmac I'm pretty sure it's the `format_null_as_str` setting. Is there any way this can be set to `0` on the test Databend instance provisioned for these CI tests? I can try to figure out how to do this from the pytest side before any tests run if required. Or, possibly a param on the connection string?

@rad-pat Adding the `format_null_as_str` in connection params is a good choice. I will make it. Thanks for your PR again.

**Pull request merged**
